### ISSUE TITLE
tweet-deleter don't work with new API limits

### ISSUE THREAD

**Issue by jleroy** [brndnmtthws/tweet-delete#133]
tweet-deleter don't work with Twitter API v2 limits. I get the following message: **You currently have access to a subset of Twitter API v2 endpoints and limited v1.1 endpoints (e.g. media post, oauth) only. If you need access to this endpoint, you may need a different access level. You can learn more here: https://developer.twitter.com/en/portal/product**.

Can we do something to avoid this limitation or there's no way to mass delete tweets anymore?

```
🐦␡ starting tweet-delete                                                    ␡🐦
🔑 validating credentials                                                     🔑
Traceback (most recent call last):
  File "/Users/jleroy/.pyvenv/tweet-delete/bin/tweet-delete", line 8, in <module>
    sys.exit(cli())
  File "/Users/jleroy/.pyvenv/tweet-delete/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jleroy/.pyvenv/tweet-delete/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/jleroy/.pyvenv/tweet-delete/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jleroy/.pyvenv/tweet-delete/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/jleroy/.pyvenv/tweet-delete/lib/python3.9/site-packages/tweet_delete/main.py", line 95, in cli
    creds = deleter.validate_creds()
  File "/Users/jleroy/.pyvenv/tweet-delete/lib/python3.9/site-packages/tweet_delete/deleter.py", line 47, in validate_creds
    return self.api.VerifyCredentials()
  File "/Users/jleroy/.pyvenv/tweet-delete/lib/python3.9/site-packages/twitter/api.py", line 4699, in VerifyCredentials
    resp = self._RequestUrl(url, 'GET', data)
  File "/Users/jleroy/.pyvenv/tweet-delete/lib/python3.9/site-packages/twitter/api.py", line 4962, in _RequestUrl
    limit = self.CheckRateLimit(url)
  File "/Users/jleroy/.pyvenv/tweet-delete/lib/python3.9/site-packages/twitter/api.py", line 4809, in CheckRateLimit
    self.InitializeRateLimit()
  File "/Users/jleroy/.pyvenv/tweet-delete/lib/python3.9/site-packages/twitter/api.py", line 4792, in InitializeRateLimit
    data = self._ParseAndCheckTwitter(resp.content.decode('utf-8'))
  File "/Users/jleroy/.pyvenv/tweet-delete/lib/python3.9/site-packages/twitter/api.py", line 4908, in _ParseAndCheckTwitter
    self._CheckForTwitterError(data)
  File "/Users/jleroy/.pyvenv/tweet-delete/lib/python3.9/site-packages/twitter/api.py", line 4928, in _CheckForTwitterError
    raise TwitterError(data['errors'])
twitter.error.TwitterError: [{'message': 'You currently have access to a subset of Twitter API v2 endpoints and limited v1.1 endpoints (e.g. media post, oauth) only. If you need access to this endpoint, you may need a different access level. You can learn more here: https://developer.twitter.com/en/portal/product', 'code': 453}]
```

**Comment by jleroy** [comment]
OK so python-twitter hasn't be updated to reflect Twitter's API changes, and the project seems to be dead : https://github.com/bear/python-twitter/issues/721.
Maybe I can try to move tweet-deleter to tweepy? It doesn't seems to be a lot of work.

**Comment by jleroy** [comment]
Apparently the new Free tier of Twitter's API only allow to post and delete 50 tweets per day:

<img width="1047" alt="Capture d’écran 2023-07-14 à 16 40 23" src="https://github.com/brndnmtthws/tweet-delete/assets/671734/cc12b436-f81b-4bd6-b508-4eec6948078c">

I'm not even allowed to read my own timeline. 
All we can do now is hope that Musk sells Twitter back quickly I guess... 🙄

**Comment by brndnmtthws** [comment]
RIP in peace Twitter 🐦

**Comment by kapoorsaumitra** [comment]
any updates on this issue?

**Comment by jleroy** [comment]
Closing as official (public) Twitter/X API access is even more restricted today and no endpoints are accessible for free anymore.
