### ISSUE TITLE
ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by mrichman** [brndnmtthws/tweet-delete#3]
Getting this error using both the pip-installed library and the Docker image:

```
👉 tweets older than 7 days will be deleted                                   👈
👉 only tweets created after 2006-03-21 00:00:00 will be deleted              👈
🦅 off we go                                                                  🦅
checking for tweets, starting from last_max_id=None
✅ done checking for tweets, tweets_read=0 max_id=0
Traceback (most recent call last):
  File "/usr/local/bin/tweet-delete", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/tweet_delete/main.py", line 67, in cli
    deleter.run()
  File "/usr/local/lib/python3.8/site-packages/tweet_delete/deleter.py", line 194, in run
    max_id = self.check_for_tweets()
  File "/usr/local/lib/python3.8/site-packages/tweet_delete/deleter.py", line 189, in check_for_tweets
    Deleter.print_stats_for('favourites', favourite_counts)
  File "/usr/local/lib/python3.8/site-packages/tweet_delete/deleter.py", line 128, in print_stats_for
    name.ljust(16), len(values), min(values), max(values),
ValueError: min() arg is an empty sequence
```

**Comment by brndnmtthws** [comment]
Oh bummer, that is indeed a problem. Let me go ahead and fix that.

**Comment by mrichman** [comment]
Thanks for responding so quickly!

**Comment by mrichman** [comment]
Thanks for the fix. Stupid question — how do I know if it's working? I'm trying to delete all my likes.

```
👉 tweets older than 7 days will be deleted                                   👈
👉 only tweets created after 2006-03-21 00:00:00 will be deleted              👈
🦅 off we go                                                                  🦅
checking for tweets, starting from last_max_id=None
✅ done checking for tweets, tweets_read=0 max_id=0
checking for tweets, starting from last_max_id=0
✅ done checking for tweets, tweets_read=0 max_id=0
```

**Comment by brndnmtthws** [comment]
Ah, it doesn't do that (yet). Currently it only deletes _your_ tweets. If you don't have any, it won't do anything.

There's another issue for that (here: #2), it's something I can probably add.

**Comment by mrichman** [comment]
I'd love to see that feature. Thanks!
