### ISSUE TITLE
<tweet_delete.deleter.Deleter object at ...> failed with AttributeError

### ISSUE THREAD

**Issue by mrichman** [brndnmtthws/tweet-delete#5]
Just started getting this error today trying to delete favorites...

```
...
checking for favorites
favorite ID=1303891849011228672 will be deleted at 2020-09-11 03:03:36
favorite ID=1303770200366440448 will be deleted at 2020-09-10 19:00:13
favorite ID=1301654288892981248 will be deleted at 2020-09-04 22:52:20
favorite ID=1282000033764843520 will be deleted at 2020-07-12 17:13:21
favorite ID=1281704059855081479 will be deleted at 2020-07-11 21:37:15
favorite ID=1275637486744752128 will be deleted at 2020-06-25 03:50:51
favorite ID=1265681708361437184 will be deleted at 2020-05-28 16:30:09
favorite ID=1263934819580420098 will be deleted at 2020-05-23 20:48:38
favorite ID=1221226536151539718 will be deleted at 2020-01-27 00:21:10
favorite ID=1192542848916369410 will be deleted at 2019-11-08 20:42:26
favorite ID=1175444645335248897 will be deleted at 2019-09-22 16:20:16
favorite ID=1150970266098515969 will be deleted at 2019-07-17 03:27:50
favorite ID=1143641126458548225 will be deleted at 2019-06-26 22:04:27
favorite ID=1095049568264310784 will be deleted at 2019-02-12 19:58:56
favorite ID=1089489112955011072 will be deleted at 2019-01-28 11:43:40
deleting favorite with ID=1303891849011228672
deleting favorite with ID=1303770200366440448
deleting favorite with ID=1301654288892981248
deleting favorite with ID=1282000033764843520
deleting favorite with ID=1281704059855081479
deleting favorite with ID=1275637486744752128
deleting favorite with ID=1265681708361437184
deleting favorite with ID=1263934819580420098
deleting favorite with ID=1221226536151539718
deleting favorite with ID=1192542848916369410
deleting favorite with ID=1175444645335248897
deleting favorite with ID=1150970266098515969
deleting favorite with ID=1143641126458548225
deleting favorite with ID=1095049568264310784
deleting favorite with ID=1089489112955011072
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run
  File "/Users/mark/Library/Python/3.8/lib/python/site-packages/tweet_delete/deleter.py", line 314, in delete_favourite
    if fav.id in self.favourites_scheduled_for_deletion:
  File "/usr/local/lib/python3.8/site-packages/twitter/models.py", line 26, in __eq__
    return other and self.AsDict() == other.AsDict()
AttributeError: 'int' object has no attribute 'AsDict'
2020-09-11T13:44:12Z <Greenlet at 0x10d428260: <bound method Deleter.delete_favourite of <tweet_delete.deleter.Deleter object at 0x10ad6ddf0>>(Status(ID=1303891849011228672, ScreenName=anjewla9)> failed with AttributeError

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run
  File "/Users/mark/Library/Python/3.8/lib/python/site-packages/tweet_delete/deleter.py", line 314, in delete_favourite
    if fav.id in self.favourites_scheduled_for_deletion:
  File "/usr/local/lib/python3.8/site-packages/twitter/models.py", line 26, in __eq__
    return other and self.AsDict() == other.AsDict()
AttributeError: 'int' object has no attribute 'AsDict'
2020-09-11T13:44:12Z <Greenlet at 0x10d428480: <bound method Deleter.delete_favourite of <tweet_delete.deleter.Deleter object at 0x10ad6ddf0>>(Status(ID=1301654288892981248, ScreenName=edjgeek,)> failed with AttributeError

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run
  File "/Users/mark/Library/Python/3.8/lib/python/site-packages/tweet_delete/deleter.py", line 314, in delete_favourite
    if fav.id in self.favourites_scheduled_for_deletion:
  File "/usr/local/lib/python3.8/site-packages/twitter/models.py", line 26, in __eq__
    return other and self.AsDict() == other.AsDict()
AttributeError: 'int' object has no attribute 'AsDict'
2020-09-11T13:44:12Z <Greenlet at 0x10d4287b0: <bound method Deleter.delete_favourite of <tweet_delete.deleter.Deleter object at 0x10ad6ddf0>>(Status(ID=1275637486744752128, ScreenName=chuckwoo)> failed with AttributeError

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run
  File "/Users/mark/Library/Python/3.8/lib/python/site-packages/tweet_delete/deleter.py", line 314, in delete_favourite
    if fav.id in self.favourites_scheduled_for_deletion:
  File "/usr/local/lib/python3.8/site-packages/twitter/models.py", line 26, in __eq__
    return other and self.AsDict() == other.AsDict()
AttributeError: 'int' object has no attribute 'AsDict'
2020-09-11T13:44:12Z <Greenlet at 0x10d428d00: <bound method Deleter.delete_favourite of <tweet_delete.deleter.Deleter object at 0x10ad6ddf0>>(Status(ID=1175444645335248897, ScreenName=chuckwoo)> failed with AttributeError

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run
  File "/Users/mark/Library/Python/3.8/lib/python/site-packages/tweet_delete/deleter.py", line 314, in delete_favourite
    if fav.id in self.favourites_scheduled_for_deletion:
  File "/usr/local/lib/python3.8/site-packages/twitter/models.py", line 26, in __eq__
    return other and self.AsDict() == other.AsDict()
AttributeError: 'int' object has no attribute 'AsDict'
2020-09-11T13:44:12Z <Greenlet at 0x10d455150: <bound method Deleter.delete_favourite of <tweet_delete.deleter.Deleter object at 0x10ad6ddf0>>(Status(ID=1095049568264310784, ScreenName=Geronimo)> failed with AttributeError

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run
  File "/Users/mark/Library/Python/3.8/lib/python/site-packages/tweet_delete/deleter.py", line 314, in delete_favourite
    if fav.id in self.favourites_scheduled_for_deletion:
  File "/usr/local/lib/python3.8/site-packages/twitter/models.py", line 26, in __eq__
    return other and self.AsDict() == other.AsDict()
AttributeError: 'int' object has no attribute 'AsDict'
2020-09-11T13:44:12Z <Greenlet at 0x10d428bf0: <bound method Deleter.delete_favourite of <tweet_delete.deleter.Deleter object at 0x10ad6ddf0>>(Status(ID=1192542848916369410, ScreenName=chuckwoo)> failed with AttributeError
```

**Comment by brndnmtthws** [comment]
This should be fixed with 9ad47c57a23e520ce06671570fd249fea09e99bf.
